version: "3.3"

services:
    jenkins:
        image: jenkins/jenkins
        container_name: jenkins
        restart: always
        privileged: true
        ports:
            - "8080:8080"
            - "50000:50000"
        networks:
            - golden_gate
        volumes:
            - jenkins_data:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
            - docker_certs:/certs/client:ro
    socat:
        image: alpine/socat:latest
        container_name: alpine-socat
        restart: always
        command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
        networks:
             - golden_gate
        volumes:
             - /var/run/docker.sock:/var/run/docker.sock
        expose:
             - "2375"
    sonarqube:
        image: sonarqube:community
        container_name: sonarqube
        restart: always
        ports:
             - "9000:9000"
        environment:
             - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
             - SONARQUBE_JDBC_USERNAME=sonar
             - SONARQUBE_JDBC_PASSWORD=sonar
        networks:
             - golden_gate
        volumes:
             - sonarqube_conf:/opt/sonarqube/conf
             - sonarqube_data:/opt/sonarqube/data
             - sonarqube_extension:/opt/sonarqube/extensions
             - sonarqube_plugins:/opt/sonarqube/lib/bundled-plugins
        depends_on:
             - sonardb
        links:
             - sonardb
    sonardb:
        image: postgres
        container_name: postgres
        restart: always
        environment:
             - POSTGRES_USER=sonar
             - POSTGRES_PASSWORD=sonar
             - POSTGRESQL_DB=sonar
             - POSTGRES_HOST_AUTH_METHOD=trust
             - PGDATA=/var/lib/postgresql/data/postgresql.conf
        ports:
             - "5432:5432"
        networks:
             - golden_gate
        volumes:
             - postgre_conf:/var/lib/postgresql/data/
networks:
    golden_gate:
        driver: bridge
volumes:
    jenkins_data: {}
    docker_certs: {}
    sonarqube_conf: {}
    sonarqube_data: {}
    sonarqube_plugins: {}
    sonarqube_extension: {}
    postgre_conf: {}